#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/deepseek_vl_v2/modular_deepseek_vl_v2.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_deepseek_vl_v2.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

from ...configuration_utils import PretrainedConfig
from ...utils import logging
from ..auto import CONFIG_MAPPING, AutoConfig


logger = logging.get_logger(__name__)


class MlpProjectorConfig(PretrainedConfig):
    model_type = "mlp_projector"
    projector_type: str = "downsample_mlp_gelu"
    input_dim: int = 1152
    n_embed: int = 2048
    depth: int = 2
    mlp_ratio: int = 1
    downsample_ratio: int = 2
    token_pooling: bool = False

    def __init__(
        self,
        projector_type: str = "downsample_mlp_gelu",
        input_dim: int = 1152,
        n_embed: int = 2048,
        depth: int = 2,
        mlp_ratio: int = 1,
        downsample_ratio: int = 2,
        token_pooling: bool = False,
        **kwargs,
    ):
        self.projector_type = projector_type if projector_type is not None else "downsample_mlp_gelu"
        self.input_dim = input_dim
        self.n_embed = n_embed
        self.depth = depth
        self.mlp_ratio = mlp_ratio
        self.downsample_ratio = downsample_ratio
        self.token_pooling = token_pooling

        super().__init__(**kwargs)


class DeepseekVLV2Config(PretrainedConfig):
    model_type = "deepseek_vl_v2"
    sub_configs = {
        "text_config": AutoConfig,
        "vision_config": AutoConfig,
        "projector_config": MlpProjectorConfig,
    }

    tile_tag: str = "2D"
    global_view_pos: str = "head"
    candidate_resolutions: tuple[tuple[int, int]] = ((384, 384),)

    def __init__(
        self,
        tile_tag: str = "2D",
        global_view_pos: str = "head",
        candidate_resolutions: tuple[tuple[int, int]] = ((384, 384),),
        text_config: dict = None,
        vision_config: dict = None,
        projector_config: dict = None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.tile_tag = tile_tag
        self.global_view_pos = global_view_pos
        self.candidate_resolutions = candidate_resolutions

        if text_config is None:
            text_config = {}
            logger.info("`text_config` is `None`. Initializing the `DeepseekV2Config` with default values.")

        if vision_config is None:
            vision_config = {}
            logger.info("`vision_config` is `None`. Initializing the `SiglipVisionConfig` with default values.")

        if isinstance(text_config, dict):
            text_config["model_type"] = text_config.get("model_type", "deepseek_v2")
            text_config = CONFIG_MAPPING[text_config["model_type"]](**text_config)

        if isinstance(vision_config, dict):
            vision_config["model_type"] = "siglip_vision_model"
            vision_config = CONFIG_MAPPING[vision_config["model_type"]](**vision_config)

        if isinstance(projector_config, dict):
            projector_config["model_type"] = "mlp_projector"
            projector_config = MlpProjectorConfig(**projector_config)

        self.text_config = text_config
        self.vision_config = vision_config
        self.projector_config = projector_config

        if getattr(self.text_config, "kv_lora_rank", None) is None:
            self.text_config.kv_lora_rank = 512
            logger.info("`kv_lora_rank` is `None`. Setting `kv_lora_rank` to 512.")

        if getattr(self.text_config, "qk_rope_head_dim", None) is None:
            self.text_config.qk_rope_head_dim = 64
            logger.info("`qk_rope_head_dim` is `None`. Setting `qk_rope_head_dim` to 64.")

        if getattr(self.text_config, "qk_nope_head_dim", None) is None or self.text_config.qk_nope_head_dim <= 0:
            self.text_config.qk_nope_head_dim = 128
            logger.info("`qk_nope_head_dim` missing or <=0. Setting to 128 for safety.")

        if getattr(self.text_config, "v_head_dim", None) is None or self.text_config.v_head_dim <= 0:
            self.text_config.v_head_dim = 128
            logger.info("`v_head_dim` missing or <=0. Setting to 128 for safety.")

        self.text_config.head_dim = self.text_config.qk_rope_head_dim


__all__ = ["DeepseekVLV2Config"]
